### ISSUE TITLE
hetu function improvement

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/sorvi#8]
hetu should be improved such that:

 1. If a single hetu is provided, the function returns a hetu object 
 1. If a vector of hetus is provided, the function returns a list of hetu objects
 1. Function argument should be added so that instead of hetu objects, a specific variable will be checked. So that the function can directly convert the hetus into gender (or other variable) vector when requested. This will save an additional step from the user.

In fact the function could return a data.frame instead of a list ? At least when hetu vector is given as input. Then any variable can be easily picked from the output without additional sapply steps.

**Comment by juuussi** [comment]
Implemented points 1-3.
